In [1]:
import pandas as pd
data=pd.read_csv("amazon_product.csv")
print(data)

    Unnamed: 0        asin                                      product_title  \
0            0  B0BQ118F2T  Moto G Play 2023 3-Day Battery Unlocked Made f...
1            1  B0CTD47P22  SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...
2            2  B0CHH6X6H2  Total by Verizon | Samsung Galaxy A03s | Locke...
3            3  B0BZ9XNBRB  Google Pixel 7a - Unlocked Android Cell Phone ...
4            4  B0CN1QSH8Q  SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...
..         ...         ...                                                ...
59          59  B0D6LWXK1R  Greatish Hits: I Followed My Dreams and My Dre...
60          60  B0CLKQF5HR                                          Swan Song
61          61  B0BZFHK12K                            Bluey: Let&#x27;s Play!
62          62  B09Z7J4L6X  Xbox Wireless Controller – Sky Cipher Special ...
63          63  B0CT2R7199  HP DeskJet 2855e Wireless All-in-One Color Ink...

   product_price product_original_price currency  product_star_rating  \
0         $99.99                $169.99      USD                  4.0
1        $149.74                $158.00      USD                  4.2
2         $49.88                    NaN      USD                  3.9
3        $335.00                $499.00      USD                  4.3
4        $199.99                    NaN      USD                  4.1
..           ...                    ...      ...                  ...
59        $34.98                    NaN      USD                  NaN
60        $14.99                 $30.00      USD                  4.4
61         $0.00                    NaN      USD                  3.5
62        $69.99                    NaN      USD                  2.6
63        $59.99                 $84.99      USD                  4.0

    product_num_ratings                           product_url  \
0                  2929  https://www.amazon.com/dp/B0BQ118F2T
1                   135  https://www.amazon.com/dp/B0CTD47P22
2                   205  https://www.amazon.com/dp/B0CHH6X6H2
3                  2248  https://www.amazon.com/dp/B0BZ9XNBRB
4                   423  https://www.amazon.com/dp/B0CN1QSH8Q
..                  ...                                   ...
59                    0  https://www.amazon.com/dp/B0D6LWXK1R
60                14471  https://www.amazon.com/dp/B0CLKQF5HR
61                  270  https://www.amazon.com/dp/B0BZFHK12K
62                   12  https://www.amazon.com/dp/B09Z7J4L6X
63                48154  https://www.amazon.com/dp/B0CT2R7199

                                        product_photo  ...  is_best_seller  \
0   https://m.media-amazon.com/images/I/61K1Fz5Lxv...  ...           False
1   https://m.media-amazon.com/images/I/51QhB2CfqS...  ...           False
2   https://m.media-amazon.com/images/I/812woqv69C...  ...           False
3   https://m.media-amazon.com/images/I/61r7cCpQPl...  ...           False
4   https://m.media-amazon.com/images/I/61s0ZzwzSC...  ...           False
..                                                ...  ...             ...
59  https://m.media-amazon.com/images/I/815otxMW0i...  ...           False
60  https://m.media-amazon.com/images/I/71dSn3QCY6...  ...            True
61  https://m.media-amazon.com/images/I/617GUqQEIC...  ...           False
62  https://m.media-amazon.com/images/I/71i2tEKlZ2...  ...            True
63  https://m.media-amazon.com/images/I/61+biEwB1h...  ...            True

   is_amazon_choice  is_prime  climate_pledge_friendly  \
0             False      True                    False
1             False      True                    False
2             False      True                    False
3             False     False                    False
4             False      True                     True
..              ...       ...                      ...
59            False     False                    False
60            False     False                    False
61            False     False                    False
62            False     False                    False
63            False     False                     True

                 sales_volume  \
0    6K+ bought in past month
1    3K+ bought in past month
2    2K+ bought in past month
3   10K+ bought in past month
4    3K+ bought in past month
..                        ...
59   50+ bought in past month
60         Print List Price:
61                Jul 7, 2023
62               Aug 13, 2024
63  80K+ bought in past month

                                             delivery has_variations  \
0                            FREE delivery Tue, Aug 6           True
1   FREE delivery Wed, Aug 7 Only 7 left in stock ...          False
2                            FREE delivery Tue, Aug 6          False
3                             FREE delivery Aug 6 - 8           True
4                            FREE delivery Tue, Aug 6           True
..                                                ...            ...
59  FREE delivery on $35 shipped by Amazon.This ti...          False
60                                Available instantly          False
61          Available instantly on compatible devices          False
62  FREE deliveryThis item will be released on Aug...          False
63                                      FREE delivery          False

                  product_availability  unit_price unit_count
0                                  NaN         NaN        NaN
1   Only 7 left in stock - order soon.         NaN        NaN
2                                  NaN         NaN        NaN
3                                  NaN         NaN        NaN
4                                  NaN         NaN        NaN
..                                 ...         ...        ...
59                                 NaN         NaN        NaN
60                                 NaN         NaN        NaN
61                                 NaN         NaN        NaN
62                                 NaN         NaN        NaN
63                                 NaN         NaN        NaN

[64 rows x 22 columns]

In [2]:
print(data.head())

   Unnamed: 0        asin                                      product_title  \
0           0  B0BQ118F2T  Moto G Play 2023 3-Day Battery Unlocked Made f...
1           1  B0CTD47P22  SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...
2           2  B0CHH6X6H2  Total by Verizon | Samsung Galaxy A03s | Locke...
3           3  B0BZ9XNBRB  Google Pixel 7a - Unlocked Android Cell Phone ...
4           4  B0CN1QSH8Q  SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...

  product_price product_original_price currency  product_star_rating  \
0        $99.99                $169.99      USD                  4.0
1       $149.74                $158.00      USD                  4.2
2        $49.88                    NaN      USD                  3.9
3       $335.00                $499.00      USD                  4.3
4       $199.99                    NaN      USD                  4.1

   product_num_ratings                           product_url  \
0                 2929  https://www.amazon.com/dp/B0BQ118F2T
1                  135  https://www.amazon.com/dp/B0CTD47P22
2                  205  https://www.amazon.com/dp/B0CHH6X6H2
3                 2248  https://www.amazon.com/dp/B0BZ9XNBRB
4                  423  https://www.amazon.com/dp/B0CN1QSH8Q

                                       product_photo  ...  is_best_seller  \
0  https://m.media-amazon.com/images/I/61K1Fz5Lxv...  ...           False
1  https://m.media-amazon.com/images/I/51QhB2CfqS...  ...           False
2  https://m.media-amazon.com/images/I/812woqv69C...  ...           False
3  https://m.media-amazon.com/images/I/61r7cCpQPl...  ...           False
4  https://m.media-amazon.com/images/I/61s0ZzwzSC...  ...           False

  is_amazon_choice  is_prime  climate_pledge_friendly  \
0            False      True                    False
1            False      True                    False
2            False      True                    False
3            False     False                    False
4            False      True                     True

                sales_volume  \
0   6K+ bought in past month
1   3K+ bought in past month
2   2K+ bought in past month
3  10K+ bought in past month
4   3K+ bought in past month

                                            delivery has_variations  \
0                           FREE delivery Tue, Aug 6           True
1  FREE delivery Wed, Aug 7 Only 7 left in stock ...          False
2                           FREE delivery Tue, Aug 6          False
3                            FREE delivery Aug 6 - 8           True
4                           FREE delivery Tue, Aug 6           True

                 product_availability  unit_price unit_count
0                                 NaN         NaN        NaN
1  Only 7 left in stock - order soon.         NaN        NaN
2                                 NaN         NaN        NaN
3                                 NaN         NaN        NaN
4                                 NaN         NaN        NaN

[5 rows x 22 columns]

In [3]:
data.head(10)

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
5,5,B0CSB22F9C,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$129.99,$137.65,USD,4.2,578,https://www.amazon.com/dp/B0CSB22F9C,https://m.media-amazon.com/images/I/51rp0nqaPo...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
6,6,B0CV4NQYFP,"SAMSUNG Galaxy A35 5G A Series Cell Phone, 128...",$349.99,$399.99,USD,4.4,109,https://www.amazon.com/dp/B0CV4NQYFP,https://m.media-amazon.com/images/I/71OznGGxhc...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6 Or fastest delivery M...",True,NaN,NaN,NaN
7,7,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,$49.39,NaN,USD,4.2,2771,https://www.amazon.com/dp/B0CHH1N9VY,https://m.media-amazon.com/images/I/71zGrrAe5N...,...,False,False,True,False,500+ bought in past month,"FREE delivery Tue, Aug 6 Or fastest delivery M...",False,NaN,NaN,NaN
8,8,B0BLZN9NDG,"SAMSUNG,Galaxy A04e (SM-A042M/DS) Dual SIM 32G...",$87.10,$105.00,USD,3.9,613,https://www.amazon.com/dp/B0BLZN9NDG,https://m.media-amazon.com/images/I/71O2YkTlq-...,...,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
9,9,B0CP6DDN1H,Moto G Play | 2024 | Unlocked | Made for US 4/...,$129.99,$149.99,USD,4.1,94,https://www.amazon.com/dp/B0CP6DDN1H,https://m.media-amazon.com/images/I/61xk4XNRkt...,...,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Aug 6 Or fastest delivery M...",False,NaN,NaN,NaN

In [4]:
data.tail()

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
59,59,B0D6LWXK1R,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,NaN,USD,NaN,0,https://www.amazon.com/dp/B0D6LWXK1R,https://m.media-amazon.com/images/I/815otxMW0i...,...,False,False,False,False,50+ bought in past month,FREE delivery on $35 shipped by Amazon.This ti...,False,NaN,NaN,NaN
60,60,B0CLKQF5HR,Swan Song,$14.99,$30.00,USD,4.4,14471,https://www.amazon.com/dp/B0CLKQF5HR,https://m.media-amazon.com/images/I/71dSn3QCY6...,...,True,False,False,False,Print List Price:,Available instantly,False,NaN,NaN,NaN
61,61,B0BZFHK12K,Bluey: Let&#x27;s Play!,$0.00,NaN,USD,3.5,270,https://www.amazon.com/dp/B0BZFHK12K,https://m.media-amazon.com/images/I/617GUqQEIC...,...,False,False,False,False,"Jul 7, 2023",Available instantly on compatible devices,False,NaN,NaN,NaN
62,62,B09Z7J4L6X,Xbox Wireless Controller – Sky Cipher Special ...,$69.99,NaN,USD,2.6,12,https://www.amazon.com/dp/B09Z7J4L6X,https://m.media-amazon.com/images/I/71i2tEKlZ2...,...,True,False,False,False,"Aug 13, 2024",FREE deliveryThis item will be released on Aug...,False,NaN,NaN,NaN
63,63,B0CT2R7199,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,$84.99,USD,4.0,48154,https://www.amazon.com/dp/B0CT2R7199,https://m.media-amazon.com/images/I/61+biEwB1h...,...,True,False,False,True,80K+ bought in past month,FREE delivery,False,NaN,NaN,NaN

In [5]:
print(data.shape)

(64, 22)

In [6]:
print(data.columns)

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='str')

In [7]:
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   64 non-null     int64
 1   asin                         64 non-null     str
 2   product_title                64 non-null     str
 3   product_price                64 non-null     str
 4   product_original_price       27 non-null     str
 5   currency                     64 non-null     str
 6   product_star_rating          54 non-null     float64
 7   product_num_ratings          64 non-null     int64
 8   product_url                  64 non-null     str
 9   product_photo                64 non-null     str
 10  product_num_offers           64 non-null     int64
 11  product_minimum_offer_price  64 non-null     str
 12  is_best_seller               64 non-null     bool
 13  is_amazon_choice             64 non-null     bool
 14  is_prime                     64 non-null     bool
 15  climate_pledge_friendly      64 non-null     bool
 16  sales_volume                 61 non-null     str
 17  delivery                     63 non-null     str
 18  has_variations               64 non-null     bool
 19  product_availability         1 non-null      str
 20  unit_price                   5 non-null      str
 21  unit_count                   5 non-null      float64
dtypes: bool(5), float64(2), int64(3), str(12)
memory usage: 26.8 KB
None

In [8]:
print(data.describe())

       Unnamed: 0  product_star_rating  product_num_ratings  \
count   64.000000            54.000000         6.400000e+01
mean    31.500000             4.244444         5.210164e+04
std     18.618987             0.558187         1.576855e+05
min      0.000000             1.800000         0.000000e+00
25%     15.750000             4.100000         4.775000e+01
50%     31.500000             4.400000         9.675000e+02
75%     47.250000             4.600000         1.384625e+04
max     63.000000             4.800000         1.015448e+06

       product_num_offers  unit_count
count           64.000000    5.000000
mean             4.859375   15.200000
std              8.145243   25.390943
min              1.000000    0.000000
25%              1.000000    2.000000
50%              1.000000    3.000000
75%              4.000000   11.000000
max             34.000000   60.000000

In [11]:
data.isnull()

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
2,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
4,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,False,False,False,False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,True,True,True
60,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
61,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
62,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
63,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True

In [9]:
print(data.isnull().sum())

Unnamed: 0                      0
asin                            0
product_title                   0
product_price                   0
product_original_price         37
currency                        0
product_star_rating            10
product_num_ratings             0
product_url                     0
product_photo                   0
product_num_offers              0
product_minimum_offer_price     0
is_best_seller                  0
is_amazon_choice                0
is_prime                        0
climate_pledge_friendly         0
sales_volume                    3
delivery                        1
has_variations                  0
product_availability           63
unit_price                     59
unit_count                     59
dtype: int64

In [10]:
print(data.duplicated())

0     False
1     False
2     False
3     False
4     False
      ...
59    False
60    False
61    False
62    False
63    False
Length: 64, dtype: bool

In [12]:
data.drop(columns=['is_amazon_choice','delivery','has_variations'],inplace=True)

In [13]:
new_column_names=[]
for i in data.columns:
    print(i.capitalize())

Unnamed: 0
Asin
Product_title
Product_price
Product_original_price
Currency
Product_star_rating
Product_num_ratings
Product_url
Product_photo
Product_num_offers
Product_minimum_offer_price
Is_best_seller
Is_prime
Climate_pledge_friendly
Sales_volume
Product_availability
Unit_price
Unit_count

In [14]:
for i in data.columns:
    new_column_names.append(i.capitalize())

In [15]:
print(new_column_names)

['Unnamed: 0', 'Asin', 'Product_title', 'Product_price', 'Product_original_price', 'Currency', 'Product_star_rating', 'Product_num_ratings', 'Product_url', 'Product_photo', 'Product_num_offers', 'Product_minimum_offer_price', 'Is_best_seller', 'Is_prime', 'Climate_pledge_friendly', 'Sales_volume', 'Product_availability', 'Unit_price', 'Unit_count']

In [16]:
data.columns=new_column_names

In [17]:
data.columns

Index(['Unnamed: 0', 'Asin', 'Product_title', 'Product_price',
       'Product_original_price', 'Currency', 'Product_star_rating',
       'Product_num_ratings', 'Product_url', 'Product_photo',
       'Product_num_offers', 'Product_minimum_offer_price', 'Is_best_seller',
       'Is_prime', 'Climate_pledge_friendly', 'Sales_volume',
       'Product_availability', 'Unit_price', 'Unit_count'],
      dtype='str')

In [18]:
data.drop_duplicates(inplace=True)

In [19]:
print(data.dtypes)

Unnamed: 0                       int64
Asin                               str
Product_title                      str
Product_price                      str
Product_original_price             str
Currency                           str
Product_star_rating            float64
Product_num_ratings              int64
Product_url                        str
Product_photo                      str
Product_num_offers               int64
Product_minimum_offer_price        str
Is_best_seller                    bool
Is_prime                          bool
Climate_pledge_friendly           bool
Sales_volume                       str
Product_availability               str
Unit_price                         str
Unit_count                     float64
dtype: object